name: lint

on:
  push:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff codespell tomli isort yapf toml
      - name: Analysing the code with ruff
        run: |
          ruff check . --fix --ignore=F401
      - name: Spelling check with codespell
        run: |
          codespell -w
      - name: Run isort
        run: |
          isort .
      - name: Running yapf
        run: |
          yapf -ir .
