name: Test Examples and Auto Merge

on:
  pull_request:
    branches:
      - testing

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Specify the version of Python you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . # Install the package in editable mode

      - name: Run example scripts
        run: |
          for script in examples/*.py; do
            echo "Running $script"
            python "$script"
          done

      - name: Check if "latest" branch exists and create if necessary
        run: |
          git fetch origin
          if ! git show-ref --quiet refs/heads/latest; then
            git checkout -b latest
            git pull
            git push origin latest
          else
            git checkout latest
          fi

      - name: Merge PR if tests pass
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin
          git checkout latest
          git merge --no-ff origin/${{ github.head_ref }} -m "Auto-merging PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          git push origin latest
