name: Test testing

on:
  pull_request:
    branches:
      - testing

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run example scripts
        run: |
          for script in examples/*.py; do
            echo "Running $script"
            python "$script"
          done

      - name: Add automerge label
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const label = 'automerge';
            const octokit = new (require('@octokit/rest'))();
            octokit.rest.issues.addLabels({
              ...context.repo,
              issue_number: context.issue.number,
              labels: [label]
            });
      
      - name: Auto Merge Pull Request
        if: success()
        uses: pascalgn/automerge-action@v0.15.0
        with:
          merge_method: merge  # or 'merge', 'rebase' based on your preference
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
