name: Test examples in main

on:
  pull_request:
    branches:
      - main

jobs:
  test-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Specify the version of Python you need

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py', '**/requirements.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache downloaded files
        uses: actions/cache@v3
        with:
          path: examples/datasets  # Replace with the actual path where files are downloaded
          key: ${{ runner.os }}-downloaded-files-${{ hashFiles('**/examples/*.py') }}
          restore-keys: |
            ${{ runner.os }}-downloaded-files-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . # Install package in editable mode

      - name: Run example scripts
        run: |
          for script in examples/*.py; do
            echo "Running $script"
            python "$script"
          done
