name: Test examples and merge

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install -e .

      #- name: Run example scripts
      #  run: |
      #    for script in examples/*.py; do
      #      echo "Running $script"
      #      python "$script"
      #    done

      - name: Add automerge label
        #if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const context2 = github.context;
            const label = 'automerge';
            await octokit.issues.addLabels({
              owner: context2.repo.owner,
              repo: context2.repo.repo,
              issue_number: context2.issue.number,
              labels: [label]
            });
      
      - name: Auto Merge Pull Request
        #if: success()
        uses: pascalgn/automerge-action@v0.15.0
        with:
          merge_method: merge  # or 'merge', 'rebase' based on your preference
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
